.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH libicq2000-config 1 "January 11, 2001"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
libicq2000-config \- configuration helper script for libicq2000
.SH SYNOPSIS
.B libicq2000-config
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B libicq2000-config
commands for easier generation of the required compilation flags to
compile with libicq2000.
.SH OPTIONS
A summary of options is included below.
.TP
.B \--help
Show help text.
.TP
.B \--version
Output libicq2000 library version information
.TP
.B \--cflags
Print pre-processor and compiler flags.
.TP
.B \--libs
Print library linking information
.TP
.B \--libs-only-L
Only print the -L/-R part of --libs
.TP
.B \--libs-only-l
Only print the -l part of --libs
.SH SEE ALSO
libicq2000.m4 - the autoconf macro for libicq2000
.br
.SH AUTHOR
This manual page was written by Barnaby Gray
<barnaby@beedesign.co.uk>.
